"""created users and stops

Revision ID: 6f712786c7ba
Revises: 
Create Date: 2025-04-01 20:39:24.487620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f712786c7ba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tpus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('hash_pass', sa.String(), nullable=True),
    sa.Column('vkid', sa.String(), nullable=True),
    sa.Column('rang', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('tpu_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tpu_id'], ['tpus.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
    import os
    from dotenv import load_dotenv
    load_dotenv()
    vkid = os.getenv('ADMIN_VK')

    op.execute(
        sa.text("""INSERT INTO users (id, name, vkid, rang) VALUES ('00000000-0000-0000-0000-000000000001',
        'Driver', '""" + vkid + """', 99)""")
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stops')
    op.drop_table('users')
    op.drop_table('tpus')
    # ### end Alembic commands ###
