"""added likes for stops"

Revision ID: bec5cfdd3454
Revises: 7dceba6eab0d
Create Date: 2025-05-19 17:11:22.404943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bec5cfdd3454'
down_revision: Union[str, None] = '7dceba6eab0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_stop',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'stop_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_stop')
    # ### end Alembic commands ###
