"""added feedbacks table

Revision ID: ec21eb8d8b60
Revises: 9562c65b3c76
Create Date: 2025-05-28 22:56:28.635678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec21eb8d8b60'
down_revision: Union[str, None] = '9562c65b3c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('mark', sa.Integer(), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('answered', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('atps_title_key', 'atps', type_='unique')
    op.create_index(op.f('ix_atps_title'), 'atps', ['title'], unique=True)
    op.create_index(op.f('ix_sections_stop_id'), 'sections', ['stop_id'], unique=False)
    op.create_index(op.f('ix_stops_name'), 'stops', ['name'], unique=False)
    op.create_index(op.f('ix_stops_tpu_id'), 'stops', ['tpu_id'], unique=False)
    op.create_index(op.f('ix_timetables_route_id'), 'timetables', ['route_id'], unique=False)
    op.create_index(op.f('ix_timetables_start'), 'timetables', ['start'], unique=False)
    op.add_column('traffics', sa.Column('round', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_traffics_route_id'), 'traffics', ['route_id'], unique=False)
    op.create_index(op.f('ix_traffics_start'), 'traffics', ['start'], unique=False)
    op.create_index(op.f('ix_users_vkid'), 'users', ['vkid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_vkid'), table_name='users')
    op.drop_index(op.f('ix_traffics_start'), table_name='traffics')
    op.drop_index(op.f('ix_traffics_route_id'), table_name='traffics')
    op.drop_column('traffics', 'round')
    op.drop_index(op.f('ix_timetables_start'), table_name='timetables')
    op.drop_index(op.f('ix_timetables_route_id'), table_name='timetables')
    op.drop_index(op.f('ix_stops_tpu_id'), table_name='stops')
    op.drop_index(op.f('ix_stops_name'), table_name='stops')
    op.drop_index(op.f('ix_sections_stop_id'), table_name='sections')
    op.drop_index(op.f('ix_atps_title'), table_name='atps')
    op.create_unique_constraint('atps_title_key', 'atps', ['title'])
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
